baseURL = "https://eoof.github.io"
languageCode = "en-us"
title = "eoof"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "eoof - All rights reserved"
enableEmoji = true
publishDir = ".."
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"

[params]
  logo = "/images/logo.jpg"
  description ="the clean blog!"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "eoof eoof"
  #thumbnail = "/images/author.png"
  thumbnail = "/images/logo.jpg"
  description = "Creator of this blog."

[params.index]
  #picture = "/images/author.png"
  picture = "images/logo.jpg"
  title = "eoof"
  subtitle = "I'm a unique placeholder. Working here and there!"
  mdtext = '''
Currently trying to get this blog running, still don't know what the blog will be about!\
**This textblock is a demonstration of the mdtext-param.**\
### This is a markdown heading
'''
  alertbar = false

[params.social]
  github = "eoof"
  #linkedin = "<username>"
  #xing = "<username>"
  #medium = "eoof"
  #twitter = "<username>"

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/"
[[menu.main]]
    name = "Imprint"
    identifier = "imprint"
    weight = 200
    url = "/static/imprint"
